version: '3'
services:
  customer1:
    image: avhost/mesos-m3s:dev
    environment:
    - FRAMEWORK_NAME=customer1
    - FRAMEWORK_HOSTNAME=${HOSTNAME}
    - PREFIX_HOSTNAME=customer1
    - PREFIX_TASKNAME=customer1
    - MESOS_USERNAME=
    - MESOS_PASSWORD=
    - MESOS_MASTER=
    - MESOS_SSL=true
    - PORTRANGE_FROM=31000
    - PORTRANGE_TO=32000
    - DOMAIN=weave.local
    - LOGLEVEL=DEBUG
    - K3S_SERVER_COUNT=1
    - K3S_AGENT_COUNT=1
    - AUTH_USERNAME=
    - AUTH_PASSWORD=
    - K3S_TOKEN=
    - REDIS_PASSWORD=
    - REDIS_SERVER=
    - BOOTSTRAP_URL=https://raw.githubusercontent.com/AVENTER-UG/mesos-m3s/master/bootstrap/bootstrap.sh
    - K3S_AGENT_LABELS=[{"key":"traefik.enable","value":"true"},{"key":"traefik.http.routers.m3s.entrypoints","value":"web"},{"key":"traefik.http.routers.m3s.service","value":"m3s-http"},{"key":"traefik.http.routers.m3s.rule","value":"HostRegexp(`example.com`, `{subdomain:[a-z]+}.example.com`)"}]
    - SKIP_SSL=true
    - SSL_CRT_BASE64=<cat server.crt | base64 -w 0>
    - SSL_KEY_BASE64=<cat server.key | base64 -w 0>
    volumes:
      - ./data/:/data
    ports:
    - 10000:10000
